### ISSUE TITLE
Node.js v17.6.0  中  Vol.Vue3 无法运行 error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by 3ddbz** [cq-panda/Vue.NetCore#228]
报错了：
PS E:\github\Vue.NetCore\Vol.Vue3版本> npm run serve

> vol.vue3@0.1.0 serve
> vue-cli-service serve

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
 INFO  Starting development server...
10% building 0/1 modules 1 active ...github\Vue.NetCore\Vol.Vue3版本\node_modules\webpack\hot\dev-server.js ./src/main.j
10% building 2/5 modules 3 active ...ode_modules\babel-loader\lib\index.js!E:\github\Vue.NetCore\Vol.Vue3版本\src\main.j
sError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\webpack\lib\NormalModule.js:417:16) 
    at handleParseError (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\webpack\lib\NormalModule.js:471:10)
    at E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\webpack\lib\NormalModule.js:503:5
    at E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\webpack\lib\NormalModule.js:358:12
    at E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\loader-runner\lib\LoaderRunner.js:214:10)  
    at iterateNormalLoaders (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\loader-runner\lib\LoaderRunner.js:221:10)  
    at E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\loader-runner\lib\LoaderRunner.js:130:11)        
    at iterateNormalLoaders (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\loader-runner\lib\LoaderRunner.js:232:2)   
    at Array.<anonymous> (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\loader-runner\lib\LoaderRunner.js:205:4)      
    at Storage.finished (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:5
5:16)
    at E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\webpack\lib\NormalModule.js:417:16) 
    at handleParseError (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\webpack\lib\NormalModule.js:471:10)
    at E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\webpack\lib\NormalModule.js:503:5
    at E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\webpack\lib\NormalModule.js:358:12
    at E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\loader-runner\lib\LoaderRunner.js:214:10)  
    at Array.<anonymous> (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\loader-runner\lib\LoaderRunner.js:205:4)      
    at Storage.finished (E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:5
5:16)
    at E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at E:\github\Vue.NetCore\Vol.Vue3版本\node_modules\graceful-fs\graceful-fs.js:123:16
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.6.0

**Comment by cq-panda** [comment]
安装node14.x版本

**Comment by 3ddbz** [comment]
降为node16.x也可以运行的，希望支持node17.x
