### ISSUE TITLE
在linux下无法使用代码在线生成器

### ISSUE THREAD

**Issue by emp479** [cq-panda/Vue.NetCore#35]
在linux下使用用在线代码生成器后，只能生成业务类，其他Vue,modele,model均无法生成。

**Comment by cq-panda** [comment]
目前只支持windows本地开发使用代码生成文件 ------------------ 原始邮件 ------------------
发件人: "emp479"<notifications@github.com>
发送时间: 2019年11月20日(星期三) 中午12:34
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Vue.NetCore] 在linux下无法使用代码在线生成器 (#35)



在linux下使用用在线代码生成器后，只能生成业务类，其他Vue,modele,model均无法生成。
 
&mdash;

**Comment by emp479** [comment]
添加业务时发生如下异常是什么什么?
服务器处理出现异常:Exception has been thrown by the target of an invocation.System.FormatException: One of the identified items was in an invalid format.
   at MySqlConnector.Core.TextRow.GetValueCore(ReadOnlySpan`1 data, ColumnDefinitionPayload columnDefinition) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextRow.cs:line 63
   at MySqlConnector.Core.Row.GetValue(Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\Core\Row.cs:line 42
   at MySqlConnector.Core.Row.GetGuid(Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\Core\Row.cs:line 127

**Comment by cq-panda** [comment]
你看下你mysql表里面的数据是不有格式不正确，比如主键Id:如果设置的是char(36)，你看下存的是不是guid的格式

**Comment by emp479** [comment]
检查过数据格式,类型都不有问题,就是读不出数据来,报500错误.

**Comment by cq-panda** [comment]
你把表结构与表数据发我看下

**Comment by emp479** [comment]
CREATE TABLE `healthaa` (
  `id` CHAR(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '""' COMMENT '健康证ID', 
  `work_id` INT(6) NOT NULL COMMENT '员工工作证号',
  `staff_name` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '参检人员姓名',
  `organization_code` VARCHAR(12) NOT NULL COMMENT '员工所属机构代码',
  `staff_post` VARCHAR(50) DEFAULT NULL COMMENT '员工所在岗位',
  `staff_rank` VARCHAR(50) DEFAULT NULL COMMENT '员工职级',
  `staff_sex` INT(1) DEFAULT NULL COMMENT '员工性别',
  `staff_age` TINYINT(2) DEFAULT NULL COMMENT '员工年龄',
  `staff_marital_status` VARCHAR(10) DEFAULT NULL COMMENT '员工婚姻状况',
  `staff_IDcardNo` VARCHAR(18) DEFAULT NULL COMMENT '员工身份证号码',
  `staff_Phone_number` INT(12) DEFAULT NULL COMMENT '员工联系电话(手机)',
  `staff_inspect_datetime` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '员工参加健康证体检时间',
  `staff_due_datetime` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '员工所持健康证到期时间',
  `Enclosure` VARCHAR(300) DEFAULT NULL COMMENT '健康证件附件照片',
  `ramark` VARCHAR(100) DEFAULT NULL COMMENT '备注信息',
  `CreateDate` DATETIME DEFAULT NULL,
  `CreateID` INT(11) DEFAULT NULL,
  `Creator` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `Modifier` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `ModifyDate` DATETIME DEFAULT NULL,
  `ModifyID` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

INSERT  INTO `healthaa`(`id`,`work_id`,`staff_name`,`organization_code`,`staff_post`,`staff_rank`,`staff_sex`,`staff_age`,`staff_marital_status`,`staff_IDcardNo`,`staff_Phone_number`,`staff_inspect_datetime`,`staff_due_datetime`,`Enclosure`,`ramark`,`CreateDate`,`CreateID`,`Creator`,`Modifier`,`ModifyDate`,`ModifyID`) VALUES ('8e68188b-a9a2-45f5-87cd-58c421b14090',123456,'张三','部门名称','联系人','L2',1,36,'已婚','111111111111',159020,'2019-11-22 23:35:21','2019-11-22 23:35:24','43','3434','2019-11-21 23:35:32',3,'34','43','2019-11-22 23:35:41',43);

**Comment by cq-panda** [comment]
获取下代码,点击同步表结构，生成 model，代码生成器已增加对mysql字段类型tinyint 的识别

**Comment by emp479** [comment]
按你说的重做了一遍，但是还是出现这个问题报500错误：
{message: "~服务器没有正确处理请求,请稍等再试!", status: false}
message: "~服务器没有正确处理请求,请稍等再试!"
status: false

**Comment by cq-panda** [comment]
我在本地测试已经没问题了，麻烦把你本地生成的model发下或者把生成的代码生删除了，生成页面的菜单也删除，重新生成试下

**Comment by cq-panda** [comment]
![image](https://user-images.githubusercontent.com/20450706/69593909-a8d40600-1035-11ea-8a15-4aff1d991657.png)
![image](https://user-images.githubusercontent.com/20450706/69593927-b8ebe580-1035-11ea-9af2-2eafa7275ee2.png)
这是我本地的，直接生成就跑起来了

**Comment by emp479** [comment]
已经跑起来了,谢谢!
