### ISSUE TITLE
优化后的代码生成器del出现错误

### ISSUE THREAD

**Issue by ajw333** [cq-panda/Vue.NetCore#38]
使用优化后的代码生成器 del 时 出现Exception has been thrown by the target of an invocation.System.NullReferenceException: Object reference not set to an instance of an object.↵   at VOL.Core.BaseProvider.ServiceBase`2.Del(Object[] keys, Boolean delList) in /Users/admin/Documents/Vue.NetCore/Vue.Net2.23/VOL.Core/BaseProvider/ServiceBase.cs:line 896   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)↵   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)↵   at VOL.Core.Controllers.Basic.BaseController`1.InvokeService(String methodName, Object[] parameters) in /Users/admin/Documents/Vue.NetCore/Vue.Net2.23/VOL.Core/Controllers/Basic/BaseController.cs:line 170↵   at VOL.Core.Controllers.Basic.BaseController`1.<>c__DisplayClass19_0.<Del>b__0() in /Users/admin/Documents/Vue.NetCore/Vue.Net2.23/VOL.Core/Controllers/Basic/BaseController.cs:line 136↵   at System.Threading.Tasks.Task`1.InnerInvoke()↵   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)↵--- End of stack trace from previous location where exception was thrown ---↵   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)↵--- End of stack trace from previous location where exception was thrown ---↵   at VOL.Core.Controllers.Basic.BaseController`1.Del(Object[] keys) in /Users/admin/Documents/Vue.NetCore/Vue.Net2.23/VOL.Core/Controllers/Basic/BaseController.cs:line 136↵   at VOL.Core.Controllers.Basic.ApiBaseController`1.Del(Object[] keys) in /Users/admin/Documents/Vue.NetCore/Vue.Net2.23/VOL.Core/Controllers/Basic/ApiBaseController.cs:line 110↵   at lambda_method(Closure , Object )↵   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()↵   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)↵   at System.Threading.Tasks.ValueTask`1.get_Result()↵   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()↵   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()↵   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)↵   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)↵   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()↵   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()↵   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)↵   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)↵   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()↵   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()↵   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)↵   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)↵   at VOL.Core.Middleware.ExceptionHandlerMiddleWare.Invoke(HttpContext context) in /Users/admin/Documents/Vue.NetCore/Vue.Net2.23/VOL.Core/Middleware/ExceptionHandlerMiddleWare.cs:line 26

**Comment by cq-panda** [comment]
获取下最新代码，还是异常的话，麻烦提供下是具体哪个页面的功能，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ajw333"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 下午5:55
收件人:&nbsp;"cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[cq-panda/Vue.NetCore] 优化后的代码生成器del出现错误 (#38)




使用优化后的代码生成器 del 时 出现Exception has been thrown by the target of an invocation.System.NullReferenceException: Object reference not set to an instance of an object.↵   at VOL.Core.BaseProvider.ServiceBase2.Del(Object[] keys, Boolean delList) in /Users/admin/Documents/Vue.NetCore/Vue.Net2.23/VOL.Core/BaseProvider/ServiceBase.cs:line 896   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)↵   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)↵   at VOL.Core.Controllers.Basic.BaseController1.InvokeService(String methodName, Object[] parameters) in /Users/admin/Documents/Vue.NetCore/Vue.Net2.23/VOL.Core/Controllers/Basic/BaseController.cs:line 170↵   at VOL.Core.Controllers.Basic.BaseController1.<&gt;c__DisplayClass19_0.<Del&gt;b__0() in /Users/admin/Documents/Vue.NetCore/Vue.Net2.23/VOL.Core/Controllers/Basic/BaseController.cs:line 136↵   at System.Threading.Tasks.Task1.InnerInvoke()↵   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)↵--- End of stack trace from previous location where exception was thrown ---↵   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&amp; currentTaskSlot)↵--- End of stack trace from previous location where exception was thrown ---↵   at VOL.Core.Controllers.Basic.BaseController1.Del(Object[] keys) in /Users/admin/Documents/Vue.NetCore/Vue.Net2.23/VOL.Core/Controllers/Basic/BaseController.cs:line 136↵   at VOL.Core.Controllers.Basic.ApiBaseController1.Del(Object[] keys) in /Users/admin/Documents/Vue.NetCore/Vue.Net2.23/VOL.Core/Controllers/Basic/ApiBaseController.cs:line 110↵   at lambda_method(Closure , Object )↵   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()↵   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)↵   at System.Threading.Tasks.ValueTask`1.get_Result()↵   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()↵   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()↵   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)↵   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)↵   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()↵   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()↵   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)↵   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)↵   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()↵   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()↵   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)↵   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)↵   at VOL.Core.Middleware.ExceptionHandlerMiddleWare.Invoke(HttpContext context) in /Users/admin/Documents/Vue.NetCore/Vue.Net2.23/VOL.Core/Middleware/ExceptionHandlerMiddleWare.cs:line 26

**Comment by ajw333** [comment]
已经使用最新的代码了，具体是用代码生成器生成的一个含有导入，保存 ，新建，删除功能的页面，保存和新建，导入，导出的功能都能正常使用，就删除功能出现上面的错误

**Comment by ajw333** [comment]
代码生成器未优化前，生成的代码以上功能都正常

**Comment by cq-panda** [comment]
你在ServiceBase.cs 中调试下方法Del看下具体是哪个值为null，谢谢

**Comment by ajw333** [comment]
调试这句Type detailType = entityType.GetCustomAttribute<EntityAttribute>().DetailTable?[0];时，时间长，获取不了信息。

**Comment by cq-panda** [comment]
你使用的是主从关系吗？是的话把主表的model截下图我看下，谢谢

**Comment by ajw333** [comment]
不是

**Comment by ajw333** [comment]
就一个表

**Comment by ajw333** [comment]
直接跨过这一句调试就出现了上面的错误

**Comment by cq-panda** [comment]
非常感谢，获取下后台代码，点下生成model(不生成也行)

**Comment by ajw333** [comment]
好的

**Comment by ajw333** [comment]
以上问题解决 ，现在就是点击生成业务类代码第一次点击时出现xhr.js:172 OPTIONS http://127.0.0.1:9991/api/builder/CreateServices?tableName=Sys_Nr&nameSpace=VOL.System&foldername=Zhengming net::ERR_CONNECTION_REFUSED
coder:1 Uncaught (in promise) 网络好像出了点问题~~  的错误，第二次点击或者多点击又正常了

**Comment by cq-panda** [comment]
![image](https://user-images.githubusercontent.com/20450706/69395547-51265980-0d1a-11ea-97ba-5fb3069a20e8.png)
这个代码生成页面上有介绍这个，常见问题也有描述

**Comment by ajw333** [comment]
好
