### ISSUE TITLE
MsSql数据库执行CodeFist的初始化更新之后创建了数据库但是默认表没有创建

### ISSUE THREAD

**Issue by AidenYan97** [cq-panda/Vue.NetCore#54]

**Comment by cq-panda** [comment]
用提供的表结构创建数据库

**Comment by AidenYan97** [comment]
我删除了上次的记录又重新初始化了一下数据库,up中有记录了.但是执行update是报错


System.Data.SqlClient.SqlException (0x80131904): 为 参数'Content' 指定的大小(8000)超过了最大允许值(4000)。
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)

VOL.Entity.DomainModels.App_News 中的Content类型为nvarchar(8000),我用的是sqlserver2012.这个最大长度在网上搜索的是4000,请问现在sqlserver2012的nvarchar最大长度支持8000吗?还是说我更改这个字段长度为4000

**Comment by cq-panda** [comment]
不要使用EF命令迁移或修改数据库，应该在代码生成器中做用同步表结构功能。
另外nvarchar(8000)是代码生成器中对数据库字段nvarchar(max)转换错误的问题，这个我会提交一版本修复nvarchar(8000)与nvarchar(max)转换的问题

**Comment by AidenYan97** [comment]
好的,再麻烦您一下,我按照文档说的,手动创建数据库,并创建了一张表(包含CreateID,Creator,CreateDate),然后直接执行后台的bat.前台bat.
登录时报错   对象名 'Sys_User' 无效。是没有创建sys_User表,不用ef时哪一步执行合并数据库并创建默认表的呢?

**Comment by cq-panda** [comment]
> 好的,再麻烦您一下,我按照文档说的,手动创建数据库,并创建了一张表(包含CreateID,Creator,CreateDate),然后直接执行后台的bat.前台bat.
> 登录时报错 对象名 'Sys_User' 无效。是没有创建sys_User表,不用ef时哪一步执行合并数据库并创建默认表的呢?

登陆默认使用的就是Sys_User表，你不应该把提供的Sys开头的表删除了。
如果不需要这些表，应该登陆后将你需要的新表在代码生成器中生成前后端代码，
比如：你要用别的表替换Sys_User,你就在代码生成器把表的前后台生成，然后在代码里面，把登陆 用到的Sys_User表手动替换成你的用户表

**Comment by AidenYan97** [comment]
我没有删除数据库,我手动创建数据库-->手动添加表(默认字段)-->bat运行后台(此时数据库没有创建默认表)-->bat运行前台
是我缺少了创建默认表的那一步.
